#!/bin/sh
cd "${0%/*}" || exit 1
. "${WM_PROJECT_DIR:?}/bin/tools/RunFunctions"
runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication checkMesh -allTopology -allGeometry || true
runApplication renumberMesh -overwrite
runApplication simpleFoam
python3 postProcess.py || echo "post-process skipped"
